# Generated by Django 2.2 on 2021-07-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecorregion',
            name='nombre',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='nombre',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='registrobioespecies',
            name='base_registro',
            field=models.CharField(blank=True, choices=[('Observacion Humana', 'Observacion_humana'), ('Especimen', 'Especimen')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='registrobioespecies',
            name='especie',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='registrobioespecies',
            name='familia',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='registrobioespecies',
            name='nombre_comun',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
